
# netlify.toml
# Arquivo de configuração para o deploy na Netlify.

[build]
  # Comando para construir o projeto Next.js.
  command = "npm run build"
  
  # Diretório de publicação que contém o resultado do build.
  # Para o Next.js, o diretório padrão é ".next".
  publish = ".next"

# O plugin do Next.js para Netlify gere automaticamente
# as funções de servidor, a renderização e o cache.
[[plugins]]
  package = "@netlify/plugin-nextjs"
